openapi: 3.0.3
info:
  title: Cashflo APIs (Internal)
  version: 1.0.0
tags:
  - name: Nova
    description: Platform for managing payments in Cashflo
paths:
  /v1/nova/payout/payment:
    post:
      summary: Create a new payment transaction in Nova
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PaymentTransaction'
            example:
              - senderAccountId: "IN123456789"
                amount: 10.00
                referenceId: "PAYOUT_IN_20231025_001"
                source: "b2b"
                recipientDetails:
                  recipientName: "John Doe"
                  ifscCode: "HDFC0000123"
                  bankAccountNumber: "9876543210"
              - senderAccountId: "IN123456789"
                amount: 1000.00
                referenceId: "PAYOUT_IN_20231025_002"
                source: "b2b"
                recipientDetails:
                  recipientName: "John Doe"
                  ifscCode: "HDFC0000123"
                  bankAccountNumber: "9876543210"

      responses:
        '201':
          description: Transaction created successfully
          content:
            application/json:
              example:
                - referenceId: "PAYOUT_IN_20231025_001"
                  message: "Transaction created successfully"
                - referenceId: "PAYOUT_IN_20231025_002"
                  message: "Duplicate reference id"
        '400':
          description: Bad request, invalid input
          content:
            application/json:
              examples:
                validationError:
                  value:
                    errorCode: "VALIDATION_ERROR"
                    errorMessage: "Invalid input, please check your request payload"
                duplicateRequest:
                  value:
                    errorCode: "DUPLICATE_REQUEST"
                    errorMessage: "Error processing the request. This request has already been processed."
components:
  schemas:
    PaymentTransaction:
      type: object
      properties:
        senderAccountId:
          type: string
          description: Buyer account id
        source:
          type: string
          description: Source of the payment request
        amount:
          type: number
          format: double
          description: Amount to be payed out
        referenceId:
          type: string
          description: Unique id from the requestor and be used for de-duplicating the payment
        recipientDetails:
          $ref: '#/components/schemas/RecipientDetails'

    RecipientDetails:
      type: object
      properties:
        recipientName:
          type: string
        ifscCode:
          type: string
        bankAccountNumber:
          type: string

